FROM node:alpine

RUN npm install npm@latest --global

RUN apk update && apk upgrade && apk add --no-cache bash git openssh ca-certificates wget

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk
RUN apk add glibc-2.27-r0.apk

WORKDIR /app
